algoritmo "calculo de consumo médio de veículo"

var
DISTANCIA, COMBUSTIVEL: real

inicio

escreval("Cálculo de consumo médio de combustível de veículos")
escreva("Digite a distância pecorrida: (km)")
leia(DISTANCIA)
escreva("Digite o combustível gasto: (lt) ")
leia(COMBUSTIVEL)
escreval("O consumo médio de combustível do seu veículo é de: ",DISTANCIA/COMBUSTIVEL,"km por litro")
 
fimalgoritmo
